expresscart:
  image: 442983821453.dkr.ecr.us-east-1.amazonaws.com/nodejs
  replicaCount: 1
  env: dev

image:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  externalPort: 1111
  internalPort: 1111

mongodb:
  enabled: true
  
