version: 2.1
orbs:
   aws-ecr: circleci/aws-ecr@0.0.2
   aws-eks: circleci/aws-eks@0.2.3
workflows:
  build-and-push:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: ${CIRCLE_BUILD_NUM}
      - aws-eks/install-helm-chart:
          chart: stable/grafana
          cluster-name: Master
          release-name: dev
          namespace: dev
          requires:
            - aws-ecr/build_and_push_image 
