executors:
  machine:
jobs:
  deploy:
    executor: machine
    steps:
      - checkout
      - run:
          name: Run build script
          command: |
            helm install --debug charts/expresscart --name manoj
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
      
