version: 2.1
description: |
  Deploy a helm chart on AWS EKS
commands:
  setup-kube:
    parameters:
      cluster:
        type: string
      namespace:
        default: default
        type: string
    steps:
    - run:
        name: Configure Kubernetes Client
        command: |
         helm install --debug .chart/expresscart --name manoj
