version: 2.1
description: |
  Deploy a helm chart on AWS EKS
commands:
  setup-kube:
    parameters:
      cluster:
        type: string
      namespace:
        default: default
        type: string
    steps:
    - run:
        name: Configure Kubernetes Client
        command: |
          aws eks update-kubeconfig --name  << parameters.cluster >>
          kubectl config set-context $(kubectl config current-context) --namespace << parameters.namespace >>
          # sanity check
          kubectl get services

  init-helm:
    parameters:
      chart:
        type: string
    steps:
    - run:
        name: Initialise Helm
        command: |
          helm init --client-only
          helm list | grep << parameters.chart >>
          # download any missing subcharts
          helm dep update
  upgrade:
    parameters:
      helmparams:
        default:
        type: string
      chart:
        type: string
    steps:
    - run:
        name: Update Cluster
        command: |
          helm upgrade << parameters.helmparams>> << parameters.chart >> . || export STATUS=$?
          # cleanup
          [ ${STATUS:-0} -eq 0 ] || helm rollback << parameters.chart >> $(helm history << parameters.chart >> | grep DEPLOYED | awk '{print $1}')
          exit ${STATUS}
executors:
  default:
    docker:
      - image: civicteam/circle-aws-kube
