orbs:
  aws-eks: circleci/aws-eks@0.2.3
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: k8s
      - aws-eks/install-helm-on-cluster:
          cluster-name: k8s
          enable-cluster-wide-admin-access: true
          requires:
            - aws-eks/create-cluster
      - aws-eks/install-helm-chart:
          chart: helm/expresscart
          cluster-name: k8s
          release-name: manoj-release
          requires:
            - aws-eks/install-helm-on-cluster
