version: 2.1
orbs:
   aws-ecr: circleci/aws-ecr@0.0.2
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: 442983821453.dkr.ecr.us-east-1.amazonaws.com
          repo: nodejs
          region: us-east-1
          tag: 0.0.1
