version: 2.1
executors:
  machine:
jobs:
  deploy:
    executor: machine
    steps:
      - checkout
      - run:
          name: Run build script
          command: |
            helm install --debug charts/expresscart --name manoj
