version: 2.1
orbs:
 
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-eks: circleci/aws-eks@0.2.3
  helm: circleci/helm@0.1.1

jobs:
  install-helm-on-cluster:
    executor: aws-eks/python
    parameters:
      cluster-name: 
        type: string
        description: Cluster name
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: k8s
          install-kubectl: true
      - helm/install-helm-on-cluster:
          enable-cluster-wide-admin-access: true
  install-helm-chart:
    executor: aws-eks/python
    parameters:
      cluster-name:
        type: string
        description: Cluster name
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: k8s
      - helm/install-helm-chart:
          chart: helm/expresscart
          release-name: Mahesh-release
  
workflows:
  deployment:
    jobs:
      - install-helm-chart:
          cluster-name: test-cluster
          requires:
            - install-helm-on-cluster
  
