orbs:
  aws-eks: circleci/aws-eks@0.2.3
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-eks/install-helm-chart:
          chart: helm/expresscart
          cluster-name: Master
          release-name: dev
      - aws-eks/delete-helm-release:
          cluster-name: Master
          release-name: dev
          requires:
            - aws-eks/install-helm-chart
