apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    name: {{ .Release.Name }}-mongodb
    app: {{ .Release.Name }}-mongodb
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  template:
    metadata:
      annotations:
        name: {{ .Release.Name }}-mongodb
        author: cloudifyops
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
      - name: expresscart-mongodb
        image: {{ .Values.mongodb.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumes:
        - expresscart-mongo-data: /data/db
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: "http"
        command: ['/bin/bash'] 
        args: ["-c", "mongod --smallfiles --logpath=/dev/null"]
volumes:
  expresscart-mongo-data:

