apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: {{ .Release.Name }}-mongodb
    {{- template "labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-mongodb
