apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-expresscart
  labels:
    name: {{ .Release.Name }}-expresscart
    {{- template "labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-expresscart
    env: {{ .Values.expresscart.env }}
